### ISSUE TITLE
cyclecloud_install.py is not working - Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed

### ISSUE THREAD

**Issue by dtizon** [CycleCloudCommunity/cyclecloud_arm#4]
The cyclecloud_install.py file is not working anymore.
because of "Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed".
I have the issue with cyclecloud versions "lastest", "7.6.0", "7.5.5"....

The last time I deployed Cyclecloud was 3 or 4 weeks ago. Was working fine with "latest" and "7.5.5"
Best regards,
Daniel
--------------------------------------------------

Error with cmd: ['yum', 'install', '-y', 'azure-cli']
Output: Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
Resolving Dependencies
--> Running transaction check
---> Package azure-cli.x86_64 0:2.0.52-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package           Arch           Version               Repository         Size
================================================================================
Installing:
 azure-cli         x86_64         2.0.52-1.el7          azure-cli          25 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 25 M
Installed size: 173 M
Downloading packages:
Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed

[stderr]

Package azure-cli-2.0.52-1.el7.x86_64.rpm is not signed
Traceback (most recent call last):
  File "cyclecloud_install.py", line 369, in <module>
    main()
  File "cyclecloud_install.py", line 354, in main
    install_pre_req()
  File "cyclecloud_install.py", line 300, in install_pre_req
    _catch_sys_error(["yum", "install", "-y", "azure-cli"])
  File "cyclecloud_install.py", line 29, in _catch_sys_error
    output = check_output(cmd_list)
  File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['yum', 'install', '-y', 'azure-cli']' returned non-zero exit status 1
".;
DEBUG: Finish sending metric.
DEBUG: 11:08:44 PM - NewAzureResourceGroupDeploymentCmdlet end processing.
DEBUG: 11:08:44 PM - NewAzureResourceGroupDeploymentCmdlet end processing.

**Comment by dtizon** [comment]
Was resolved by the AzureCLI team, following another ticket I opened
https://github.com/Azure/azure-cli/issues/7983#issuecomment-444322934
